mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  leftWheelb_effort_controller:
    type: effort_controllers/JointEffortController
    joint: rightb_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightWheelb_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leftb_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  
