<?xml version="1.0"?>

<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.6"/>
  <xacro:property name="chassisLength" value="6"/>
  <xacro:property name="chassisWidth" value="1.5"/>
  <xacro:property name="chassisMass" value="0.05"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="0.01"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.4"/>
  <xacro:property name="wheelPos" value="4"/>
  <xacro:property name="wheelMass" value="25"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.01"/>

  <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
  <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

<link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>


  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
    <box size="${chassisLength-1} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual name="visual">
      
      <origin xyz="-0.78 0.75 0" rpy="0 0 ${PI/2}"/>
      <geometry>
        <mesh filename="/home/kpit/.gazebo/models/car_volvo/meshes/volvo.dae">
        </mesh>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>



<!--
  <joint name="fixed" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
  </joint>

  <link name="caster_wheel">

    <collision>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
  <sphere radius="${casterRadius}"/>
      </geometry>
    </collision>
  
    <visual> 
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
  <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>
-->

  <wheel lr="leftf" tY="-1" fb="1" f_factor="0" m_factor="0.1"/>
  <wheel lr="rightf" tY="1" fb="1" f_factor="0" m_factor="0.1" />
  <wheel lr="leftb" tY="-1" fb="-1" f_factor="1000000" m_factor="1"/>
  <wheel lr="rightb" tY="1" fb="-1" f_factor="1000000" m_factor="1"/> 

  <joint name="camera_joint" type="fixed">
    <origin xyz="2.43 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="back_camera"/>
  </joint>

<!--  First Back camera  -->
  <link name="back_camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>

  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>
<!--  Front camera  -->
<joint name="camera2_joint" type="fixed">
    <origin xyz="-2.54 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 ${PI}"/>
    <parent link="chassis"/>
    <child link="front_camera"/>
  </joint>


<link name="front_camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
      <geometry>
  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
      <geometry>

  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>

<joint name="hokuyo_joint" type="fixed">
    <origin xyz="-2.54 0 ${cameraSize+wheelRadius+cameraSize/2-0.15}" rpy="0 0 ${PI}"/>
    <parent link="chassis"/>
    <child link="hokuyo_link"/>
  </joint>

 <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="hokuyo.dae" />
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

</robot>